// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6yWmzxrj-ezbd03e3sOivAt3hfHv7kpQ',
    appId: '1:346191922590:web:2ea54c5dc1574af88a828f',
    messagingSenderId: '346191922590',
    projectId: 'trainr-4f85a',
    authDomain: 'trainr-4f85a.firebaseapp.com',
    storageBucket: 'trainr-4f85a.appspot.com',
    measurementId: 'G-3BL5X6G2ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj087MGkZGhQt0Yh6OOuuVMxCNnPDS-ig',
    appId: '1:346191922590:android:b3832164c14763378a828f',
    messagingSenderId: '346191922590',
    projectId: 'trainr-4f85a',
    storageBucket: 'trainr-4f85a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFz3JBTdHG7pgY3pkpDEIhzHFnYiDBMi4',
    appId: '1:346191922590:ios:c0c66efdd629a6d78a828f',
    messagingSenderId: '346191922590',
    projectId: 'trainr-4f85a',
    storageBucket: 'trainr-4f85a.appspot.com',
    iosBundleId: 'com.example.trainr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFz3JBTdHG7pgY3pkpDEIhzHFnYiDBMi4',
    appId: '1:346191922590:ios:ded1e862953b34498a828f',
    messagingSenderId: '346191922590',
    projectId: 'trainr-4f85a',
    storageBucket: 'trainr-4f85a.appspot.com',
    iosBundleId: 'com.example.trainr.RunnerTests',
  );
}
